apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: self-hosted-runners
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: samuelBarreto/python-app
      labels:
        - self-hosted
        - linux
        - x64
      env:
        - name: DOCKER_ENABLED
          value: "true"
      resources:
        limits:
          cpu: "1.0"
          memory: "1Gi"
        requests:
          cpu: "0.5"
          memory: "512Mi"